### ISSUE TITLE
how to set a timer with jGrowl

### ISSUE THREAD

**Issue by ypf168326** [stanlemon/jGrowl#45]
Hi

I wirte a function on my page, this function will check the order from backend, I use ajax to do this, if there is order from backend, then invoke jGrowl to show message, but i tried many times, it didn't work.
the error was "**Uncaught TypeError: undefined is not a function**",below is my code,please help me to check is anytiny wrong with jGrowl.

	(function($){
		$(function(){
			getUnreadOrder();
		});
	})(jQuery);
	
	function getUnreadOrder() {
		$.ajax({
			type : "POST",
			url : "${ctx}/store/storeBook!getUnreadOrders.do",
			dataType : 'json',
			async:false,
			success : function(data) {
				var len = data.length;
				if (len > 0) {
					$.jGrowl("You have a latest order!", {
						header: 'Header',
						life: 5000,
						theme:  'manilla',
						speed:  'slow'
					});
				}
			},
			error : function() {
				
			}
		});
		setTimeout("getUnreadOrder()",10000);
	}

**Comment by stanlemon** [comment]
This is not a jGrowl bug.

Try changing this line
```
setTimeout("getUnreadOrder()",10000);
```
to
```
setTimeout(getUnreadOrder,10000);
```
