### ISSUE TITLE
jquery-ui style not overloaded

### ISSUE THREAD

**Issue by excentris** [stanlemon/jGrowl#49]
From what I see on the `jgrowl.core.less` file [here](https://github.com/stanlemon/jGrowl/blob/master/less/jgrowl.core.less#L57) the jquery-ui `.ui-state-highlight` (among others) is meant to be overloaded. In the examples this looks alright, but if the jquery-ui css is included the style is not overloaded. Maybe the wrong css selector is generated?

**Comment by stanlemon** [comment]
Hi @excentris I haven't used jQuery UI in a very long time so that is entirely possible.  Do you have an example or jsfiddle you can show me where the issue occurs?  Thanks for your contribution!

**Comment by excentris** [comment]
Hi @stanlemon, [here you can see the issue](https://jsfiddle.net/excentris/7ogpaur3/8/), the jquery-ui style is not correctly overloaded. Without including jquery-ui the messages are styled [like they used to](https://jsfiddle.net/excentris/7ogpaur3/9/), in black with white letters. And you are very welcome!

**Comment by stanlemon** [comment]
@excentris I believe if you set the option ```themeState``` to an empty string it should turn off the jquery-ui styling. Check out https://jsfiddle.net/7ogpaur3/10/

**Comment by excentris** [comment]
@stanlemon Yes indeed! Sorry I did not see that. You can close this issue. Thanks!

**Comment by stanlemon** [comment]
No worries, thank for using jGrowl! :)
