### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by kiquenet** [stanlemon/jGrowl#55]
http://stanlemon.net/projects/jgrowl.html not found

**Comment by stanlemon** [comment]
@kiquenet Where did you find this URL referenced?

**Comment by frederickjh** [comment]
I am guessing this is related to [this issue](https://www.drupal.org/node/2529052) in the [drupal.org](http://drupal.org) issue queue for the [Nice Messages module](http://dgo.to/nicemessages), which says this link was in the README.txt but has been fixed. Which I think  means you can close this as fixed.

**Comment by stanlemon** [comment]
Thanks @frederickjh !
