### ISSUE TITLE
Bower is missing the css

### ISSUE THREAD

**Issue by patrikx3** [stanlemon/jGrowl#57]
Hello,

I think the bower is missing the css.
I think it needs.

![image](https://cloud.githubusercontent.com/assets/4770180/19036711/e10ea64a-8971-11e6-896d-d58774c478ce.png)

**Comment by patrikx3** [comment]
You just add me the authentication for bower, I have fixed the NuGet as well.

**Comment by patrikx3** [comment]
I love this :)

**Comment by patrikx3** [comment]
![image](https://cloud.githubusercontent.com/assets/4770180/19052333/a98b6222-89b6-11e6-994b-c48058545708.png)

**Comment by stanlemon** [comment]
I don't understand why it wouldn't be included in bower, doesn't bower just pull from github?

**Comment by patrikx3** [comment]
It is missing in the bower.
![image](https://cloud.githubusercontent.com/assets/4770180/20969754/c25f249e-bc8a-11e6-861d-294eea5b8c91.png)
It should be like: main: ['jgrowl.js', 'jgrowl.css']

Right now it is only JS, missing the CSS, that is why.

**Comment by patrikx3** [comment]
Like this, for materialize, can you just add it in the CSS?

![image](https://cloud.githubusercontent.com/assets/4770180/20969820/029d830c-bc8b-11e6-9405-132129d01fbd.png)

**Comment by patrikx3** [comment]
It downloads the files, but it is missing the main and cannot you automatically use Grunt and Wiredep.
That is everyone uses, I add it in, just a flag in the ```main``` in ```bower.json```.

**Comment by patrikx3** [comment]
# Just this is all
```json
{
  "name": "jGrowl",
  "version": "1.4.5",
  "homepage": "https://github.com/stanlemon/jGrowl",
  "authors": [
    "Stan Lemon <stosh1985@gmail.com>"
  ],
  "description": "jGrowl is an unobtrusive notification system for web applications.",
  "main": [
    "jquery.jgrowl.js",
    "jquery.jgrowl.css"
  ],
  "keywords": [
    "growl",
    "jgrowl",
    "jquery",
    "toaster",
    "notification",
    "message"
  ],
  "license": "MIT",
  "dependencies": {
    "jquery": ">=1.4"
  },
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ]
}
```

**Comment by patrikx3** [comment]
If you want I can remove ES6, and change to old JS. It is only for the tests.
