### ISSUE TITLE
closerTemplate property

### ISSUE THREAD

**Issue by kaelsantini** [stanlemon/jGrowl#59]
The closerTemplate property not working.

I think the line 331 must be:
`$(o.closerTemplate)` ...

**Comment by stanlemon** [comment]
```closerTemplate``` is not intended to be controlled as a per message option, it's controlled by setting ```$.jGrowl.defaults.closerTemplate``` because it effects the way that jGrowl runs as a hole.  Imagine trying to set this on every message, you wouldn't want the close all button to change with every message.
