### ISSUE TITLE
Will there be a nuget package for v1.4.5

### ISSUE THREAD

**Issue by shreedhark** [stanlemon/jGrowl#61]
Hi there, I found this package on nuget, but it is version 1.4.0.
That version has an issue which prevents it from working with jQuery 3.x. I see in the commits that this issues has been fixed in 1.4.5 but there is no nuget package updated. 

Will you be publishing an update to the nuget?

**Comment by stanlemon** [comment]
Hi @shreedhark I do not publish the nuget package, someone else must have done that so I am not sure I am able to help here.

**Comment by stanlemon** [comment]
@patrikx3 Are you able to help out @shreedhark and maybe get the 1.4.6 release I just tagged up on Nuget, it looks like you're an owner over there. Thanks!

**Comment by patrikx3** [comment]
@shreedhark updated
