### ISSUE TITLE
Node 8 and NPM 5

### ISSUE THREAD

**Issue by vcraescu** [stanlemon/jGrowl#68]
https://github.com/stanlemon/jGrowl/blob/master/package.json#L9
Isn't that "src" field actually be "main". On node 8 and NPM 5 i can't require the module because it can't find the "main" field.

**Comment by stanlemon** [comment]
I think you are correct! Do you want to open a PR for that change (to give credit where credit is due)? If not, no worries and I'll make it - just let me know.  Thanks for opening an issue!

**Comment by vcraescu** [comment]
sure, i will come up with a PR. Just wanted to make sure that's exactly the problem :).

Thanks!

**Comment by RyanGosden** [comment]
A fix for this would be great. In order to require, I had to add jgrowl to my resolve in my webpack configuration. Although this only requires the js and not the CSS  :)

**Comment by stanlemon** [comment]
I pushed up 1.4.6 with the change, let me know @vcraescu & @RyanGosden if that doesn't work for some reason.

**Comment by vcraescu** [comment]
@stanlemon works for me! Thanks!

**Comment by RyanGosden** [comment]
@stanlemon - I removed from webpack's resolve/alias  and it works a charm :+1:
