### ISSUE TITLE
Localization of label(s)

### ISSUE THREAD

**Issue by curtisgibby** [stanlemon/jGrowl#71]
What can be done to help automate the translation of label(s) in the app? Currently, I only see 

```javascript
closerTemplate:	'<div>[ close all ]</div>'
```

as a label, but there may be others that I've missed.

I would imagine that you'd just need to override the default `closerTemplate` (and any other English-based strings that may exist) when you instantiate the jGrowl object, which isn't hard in and of itself. Other projects, like [jQuery UI](https://github.com/jquery/jquery-ui/tree/master/ui/i18n) and [datatables](https://datatables.net/plug-ins/i18n/), have official or semi-official localization files to allow you to automatically override any strings. Something like this would be helpful in jGrowl as well.

**Comment by stanlemon** [comment]
@curtisgibby I think this is the only text that's supplied, so the best bet there IMO is just to change it.  A full localization implementation feels a little heavy handed to me.
