### ISSUE TITLE
Closer All

### ISSUE THREAD

**Issue by Craigy-** [stanlemon/jGrowl#73]
Can't configure options of this element. Seems like it use only default values.

**Comment by stanlemon** [comment]
@Craigy- Because it applies to the whole container of notifications and not the individual message you are correct, it's configured only at the 'defaults' level.

**Comment by Craigy-** [comment]
I need to change theme: 'themeName' and it apllies only for notifications, not for 'closer'. I think it's a bug.

**Comment by stanlemon** [comment]
Have you looked at the example included in the project? I believe there is a styled closer in there.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Craigy-** [comment]
Ok, thanks. 'closerTemplate' can help me. But it's stange a little :)

**Comment by stanlemon** [comment]
@Craigy- yeah I agree, I'd love to do an overhaul of this some day where it's more oriented around containers, so such a thing can be changed more easily - but that would also make the bar of entry a little steeper too.

**Comment by Craigy-** [comment]
It will be great :)
