### ISSUE TITLE
growl message does not close after it time outs until the hovered mouse is removed

### ISSUE THREAD

**Issue by vkadri** [stanlemon/jGrowl#74]
1. Bring up the following url -  http://jsbin.com/yobowefoqo/1/edit?html,css,output
2. Click "Create new message" link more than 2 times 
3. Hover mouse on "Close All" option located at the bottom of the last growl message 
4. Now move the mouse over the growl message and sit idle 

**Expected:** Growl meesage should close after it times out 
**Actual:
[TNAV-20313-growl_does_not_close.zip](https://github.com/stanlemon/jGrowl/files/1598655/TNAV-20313-growl_does_not_close.zip)

** Growl message does not close after it times out

**Comment by stanlemon** [comment]
Hey thanks for reaching out, however the behavior you describe is actually intended. This library pauses the automated dismissal (very similar to the actual Growl library that used to be so popular on Mac OS X). The thinking here has always been that if you are hovering over the notification you are reading it, and thus this mechanism allows a user to pause the dismissal until they are done reading.
