### ISSUE TITLE
Latest code does not match up with published NPM

### ISSUE THREAD

**Issue by marcaaron** [stanlemon/jGrowl#79]
Just noticed that the current state of this code does not match up with the version published to NPM. 

Can it be updated? For now, I'm pointing `package.json` to the last commit, but it would be great if someone could confirm this and re-publish to NPM. 🙏

**Comment by stanlemon** [comment]
Pushed a change to the package.json file and published to npm. Thanks for using jGrowl!

**Comment by marcaaron** [comment]
Amazing! Thanks so much!
