### ISSUE TITLE
I'm a hack admin of a Friendica site and this error is cryptic [RuntimeException]

### ISSUE THREAD

**Issue by WNYmathGuy** [stanlemon/jGrowl#80]
I see this big red panel failure message during the `php ~/bin/composer update` command for Friendica maintenance and I don't know what it means or how to make it right. I'm not very skilled with composer, git or being a knowledgable admin. I activate a lot of plugins for my Friendica site so I don't even know why this is generated.

<pre><span style="background-color:#CC0000"><font color="#D3D7CF">                                                                                                                                                                                </font></span>
<span style="background-color:#CC0000"><font color="#D3D7CF">  [RuntimeException]                                                                                                                                                            </font></span>
<span style="background-color:#CC0000"><font color="#D3D7CF">  Failed to execute git clone --mirror &apos;git+ssh://git@github.com/stanlemon/jGrowl.git&apos; &apos;/home/outmathadmin/.cache/composer/vcs/git-ssh---git-github.com-stanlemon-jGrowl.git/&apos;  </font></span>
<span style="background-color:#CC0000"><font color="#D3D7CF">                                                                                                                                                                                </font></span>
<span style="background-color:#CC0000"><font color="#D3D7CF">  Cloning into bare repository &apos;/home/outmathadmin/.cache/composer/vcs/git-ssh---git-github.com-stanlemon-jGrowl.git&apos;...                                                        </font></span>
<span style="background-color:#CC0000"><font color="#D3D7CF">  git@github.com: Permission denied (publickey).                                                                                                                                </font></span>
<span style="background-color:#CC0000"><font color="#D3D7CF">  fatal: Could not read from remote repository.                                                                                                                                 </font></span>
<span style="background-color:#CC0000"><font color="#D3D7CF">                                                                                                                                                                                </font></span>
<span style="background-color:#CC0000"><font color="#D3D7CF">  Please make sure you have the correct access rights                                                                                                                           </font></span>
<span style="background-color:#CC0000"><font color="#D3D7CF">  and the repository exists.                                                                                                                                                    </font></span>
<span style="background-color:#CC0000"><font color="#D3D7CF">                                                                                                                                                                                </font></span>
</pre>

**Comment by stanlemon** [comment]
Hi @WNYmathGuy this is a problem with an SSH key you have configured, not an issue with this repository.

**Comment by WNYmathGuy** [comment]
> Hi @WNYmathGuy this is a problem with an SSH key you have configured, not an issue with this repository.

@stanlemon 
With a jovial tone, I say, you closed the issue but the message is still cryptic.

Also, as a self-identified hack admin I don't know what I could do to remedy that problem. My keys ar mostly automated via the Virtualmin management software, and it makes them from LetsEncrypt's system. I've made a few with shell commands but those were for the Postfix mail system. I never made any specific ones for a Friendica servers Git-based install. 

However, due to a seemingly unrelated problem, about a year ago or less, the Composer update/install commands complained about a `Chart.js` problem which had a solution of going on Github and making a Personal Access Token that allowed the Chart.js part to work. Github seems to be sunsetting those certificates. Also after recently hearing back from Nick Downie, who appears to be the Friendica legacy link to Chart.js, https://github.com/nnnick, it is now known that he moved that to its own organization and is community managed.at https://github.com/chartjs/Chart.js

Perhaps if Friendica fixes that linking issue and we all get rid of the personal access token, the problem in my IP will go away? Any more thoughts about that?

**Comment by MrPetovan** [comment]
Hi @stanlemon an sorry about the disturbance, we're providing support over in https://github.com/friendica/friendica/issues/8510 and it definitely doesn't have anything to do with jGrowl we're happy to use at Friendica.
