### ISSUE TITLE
jGrowl including its own jQuery v3 when imported via Yarn/Webpack

### ISSUE THREAD

**Issue by lawso017** [stanlemon/jGrowl#88]
Hi there -- been a long-time user of jGrowl in a legacy Rails app that we're migrating to Yarn/Webpack for dependency management.

At the moment, when I include jGrowl in our package.json file:

`"jgrowl": "^1.4.6",`

and run `yarn install`, the jGrowl module that shows up in `node_modules` also brings along its own `node_modules` subfolder, including its own jQuery v3.6.0.

We've been using JGrowl version 1.4.6 for a while but have been back on jQuery 2.x... and have never noticed a problem. However, the jGrowl package.json specifies jQuery ^3.4.1.

So... as you can imagine Webpack then ends up loading two copies of jQuery: the global v2.x that we install first, and the version 3.4 brought along by jGrowl. 

jGrowl is then being attached to this second v3 jQuery instead of the first v2.x jQuery we install and export as a global for use by our legacy JS... so our legacy JS cannot access jGrowl.

I've confirmed that jGrowl *does* work as expected if I manually delete jGrowl's node_modules folder -- that removes the conflicting copy of jQuery and everything appears to work.

Which leads to the question:

*Is jGrowl 1.4.6 only compatible with jQuery 3+?*

I'm hoping that if 1.4.6 does in fact work with jQuery 2.x, perhaps adjusting the dependency in the package.json will fix the install issue.

Thanks in advance for any thoughts -- kind of miss the days when questions and issues were actually about using libraries, instead of just installing them...

**Comment by lawso017** [comment]
In the meantime, I've found that installing 1.4.5 works fine -- it does not define a jQuery version dependency in its package.json. If 1.4.6 actually requires jQuery 3, then can close the issue on that basis.

**Comment by stanlemon** [comment]
@lawso017 would doing this cover your situation? https://github.com/stanlemon/jGrowl/pull/89/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R27-R30

**Comment by lawso017** [comment]
Yes indeed -- believe that is a perfect solution!
https://nodejs.org/en/blog/npm/peer-dependencies/

**Comment by stanlemon** [comment]
Good deal. I'll merge this tonight and push a new version to NPM.

**Comment by lawso017** [comment]
Note to future self -- also discovered that Yarn is part of the problem in this case; Yarn is aggressively loading sub-dependencies even when an existing dependency will satisfy a jQuery plugin's requirement. 

Example... your project requires jQuery "^2.0.0"... a plugin requires jQuery ">1.8.0". If the current version of jQuery is 3.4.0, Yarn will install v3.4.0 for the plugin even though the already-available 2.2.0 would be sufficient.

So in addition to the library declaring jQuery as a "peer dependency", another solution when using Yarn is to specify a project-level version override via a "resolutions" block in the package.json file:

```
  "resolutions": {
    "jquery": "^2.0.0"
  }
```

For more info see here:
https://stackoverflow.com/questions/40108172/webpack-jquery-plugin-loading-its-own-instance-of-jquery

**Comment by stanlemon** [comment]
v1.4.8 is now on NPM, hope that helps, good luck!
