### ISSUE TITLE
accessibility

### ISSUE THREAD

**Issue by rober423** [stanlemon/jGrowl#90]
Hi there. I am using jGrowl on my website, and working on accessibility improvements to said website. I noticed this discussion the owner of this repo had about accessibility: [https://stackoverflow.com/questions/42764836/can-screen-reader-like-jaws-read-jgrowl-message](https://stackoverflow.com/questions/42764836/can-screen-reader-like-jaws-read-jgrowl-message) but it looks like this was never followed up with any changes in the repository.

The only change that actually needs to happen for jGrowl to be much more accessible is for any div with id="jGrowl" to also have attributes role="alert" and aria-live="polite". Of course if you want to be even more accessible you should allow the $.jGrowl function to optionally accept a boolean for changing to aria-live="assertive" if true.

The other small change would be to add aria-label="close" to the x buttons, since right now a screenreader will read this as a multiplication sign.

I hope this helps the owner of this repo and anyone using jGrowl in the future!

**Comment by stanlemon** [comment]
Hey @rober423 thanks for reaching out with this helpful advice! Please feel free to submit a PR with these suggestions.

**Comment by rober423** [comment]
Hi @stanlemon I'm actually working on a fork of @uxmz 's [repo](https://github.com/uxmz/jGrowl). I starting back up on this when I got laid off from work. It has a few new options to make accessibility even better. After I am able to get my changes into organized commits, I'll put it up and let you know.

**Comment by stanlemon** [comment]
Sounds great, please open a PR when you're ready, thanks!
