### ISSUE TITLE
JQuery 3 deprecations

### ISSUE THREAD

**Issue by ndegroot** [stanlemon/jGrowl#91]
I forked your JGrowl work, to make it jQuery 3 compatible using jQuery-migrate 3.4.0.js.  In the process Grunt complained about a possible unsafe version of jshint which it replaced.  I'm not a Javascript expert, just used the standard jQuery replacements for the deprecated functions. I couldn't get the Corners plugin support to work, I had to comment it out.

I can make a PR if you want, but althought I'm using the 'new' version successfully, I'm not sure it is useful and it's not fully tested.

**Comment by PRO-BROS** [comment]
Very well. Facing the same issue but now resolved on my [site](https://prhocoding.com/)

**Comment by stanlemon** [comment]
If you have a PR or even a branch somewhere I'm happy to take a look and see what we can do to move this forward and incorporate it.
